md-tangle configurations/bash.md -f -d dist/
md-tangle configurations/bin.md -f -d dist/bin/
md-tangle configurations/conkeror.md -f -d dist/
md-tangle configurations/conky.md -f -d dist/
md-tangle configurations/emacs.md -f -d dist/
md-tangle configurations/git.md -f -d dist/git/
md-tangle configurations/i3.md -f -d dist/i3/
md-tangle configurations/ideavimrc.md -f -d dist/
md-tangle configurations/nano.md -f -d dist/
md-tangle configurations/nvim.md -f -d dist/nvim/
md-tangle configurations/tmux.md -f -d dist/tmux/
md-tangle configurations/wezterm.md -f -d dist/
md-tangle configurations/xmodmap.md -f -d dist/
